INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL','2',97);
INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL','2',23);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',25);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C','2',89);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','3',89);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','3',54);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','1',50);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C#','3',30);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','1',96);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','1',71);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','2',37);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','1',49);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',84);
INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL','1',49);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',18);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','3',35);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','3',49);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',46);
INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL','3',46);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','3',77);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','2',35);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C','1',22);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','1',86);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','1',68);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','1',74);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Swift','3',100);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','2',61);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','1',20);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C','2',51);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','3',49);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',68);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C#','2',56);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Swift','1',72);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','2',7);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','2',57);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','3',82);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','1',62);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','1',88);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',69);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C#','3',18);
INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL Server','3',23);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','Vue','3',20);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',8);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','1',88);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','1',100);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','2',68);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','3',69);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','1',64);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','3',87);
INSERT INTO register_specialty_user VALUES (null, 'Dados','SQL Server','2',15);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Swift','1',57);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','2',71);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','3',52);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',18);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Java','3',89);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Java','3',1);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','1',44);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','1',57);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','3',31);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','1',64);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','3',78);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','3',39);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Java','1',47);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','2',91);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C','3',2);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',9);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','Vue','1',15);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C#','3',63);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','3',38);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','1',76);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','1',64);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','1',37);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','2',12);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',1);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','1',96);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','3',10);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','1',9);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',24);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','2',48);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','3',85);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','JavaScript','2',96);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','2',34);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','Vue','2',59);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','3',61);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Kotlin','2',4);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','1',52);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Java','2',65);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C#','1',50);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','2',80);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','3',45);
INSERT INTO register_specialty_user VALUES (null, 'Backend','Ruby','3',45);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','3',3);
INSERT INTO register_specialty_user VALUES (null, 'Dados','Python','2',48);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C','3',50);
INSERT INTO register_specialty_user VALUES (null, 'Backend','C++','3',71);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Swift','1',60);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','Objective C','1',23);
INSERT INTO register_specialty_user VALUES (null, 'Mobile','React Native','3',57);
INSERT INTO register_specialty_user VALUES (null, 'Backend','PHP','2',61);
INSERT INTO register_specialty_user VALUES (null, 'Frontend','React','1',3);
